logging:
    level:
        org:
            springframework:
                web: INFO
server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    searchPaths: src/main/resources/configuration
                    skip-ssl-validation: true
                    uri: https://github.com/shayan009/config_server_demo
    profiles:
        active: native
